### PR TITLE
:FC-1343: :zap: Integration Tests

### PR DESCRIPTION
**Pull request by agalagade**

### CODE REVIEW

**Review by busybeaver — COMMENTED** [review]
Mostly checked the `FaaSIntegrationClientTest.java` file and the GH workflows which look fine I think.

Questions:
* Do we need Unit Tests for the new files that were added to the `src/main/**` folder?
* The Integration Tests seem to fail in this PR, is that a problem?

**Comment by agalagade** [comment]
> Mostly checked the `FaaSIntegrationClientTest.java` file and the GH workflows which look fine I think.
> 
> Questions:
> 
> * Do we need Unit Tests for the new files that were added to the `src/main/**` folder?
> * The Integration Tests seem to fail in this PR, is that a problem?

* The Integration Tests are working fine; see here: https://github.com/agalagade/faas-client-jdk/pull/1; the reason it's failing here is due to the environment variables, as it seems GitHub does not provide secrets to the PR coming from the forked repo branch
* Do we need Unit Tests for the new files that were added to the `src/main/**` folder - I did not add their unit tests since the files I added are only being used for the integration tests

**Comment by busybeaver** [comment]
Okay, yes. That's a security measure to not expose secrets to forks (which makes sense).

If these new files are only needed during tests, I recommend moving them to the `src/test/` folder. Everything that is (only) test-related should reside there. It also prevents that these new files are included in the jar file. And since these files are only used for tests, no need to include them in the final package.

**Comment by busybeaver** [comment]
Looks good I think. We should just ensure/verify that the integration tests work fine after merging the PR (when the secrets are present)

**Review by chrbrt — APPROVED** [review]

**Pull request merged**
